Allow dt > 1
mrc-ide/dust2 pull request #141
Opened 2024-11-22 13:17 UTC by weshinsley

2024-11-23 17:34 UTC, weshinsley commented
Well - that test does now work by just not calling the checks that would prevent it from doing so if dt > 1 - not sure if this is the answer. But also not sure what checks should/can be carried out at that point (interface.R:700) if dt > 1...

2024-12-13 10:41 UTC, richfitz requested changes

2024-12-13 10:41 UTC, richfitz commented on DESCRIPTION
> +Version: 0.3.12
can you rebase/merge and update, then we can merge this

2024-12-13 13:07 UTC, richfitz approved these changes

2024-12-13 13:08 UTC, merged